---
services:
  uptimekuma:
    image: louislam/uptime-kuma
    container_name: Uptime-Kuma
    hostname: uptimekuma
    mem_limit: 2g
    cpu_shares: 1024
    ports:
      - 3444:3001
    volumes:
      - /data/projects/uptimekuma/data:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Australia\Adelaide
    restart: unless-stopped
